### ISSUE TITLE
Unknown Station defined in Route #0

### ISSUE THREAD

**Issue by RaphaelWimmer** [gaudes/ioBroker.fahrplan#290]
As of yesterday, the adapter is no longer able to retrieve timetable information.
The log contains the following error messages (or variations):

```
Unknown Station defined in Route #0
Unknown Station defined in Departure Timetable #0
fahrplan.0 | 2023-04-03 08:10:17.700 | error | Error  occured: HAFAS error in Station in fStation/verifyStation [Error:  Writer error:  root.svcResL.svcResL.res.common.locL.locL.gridL.gridL.nCols(no value  assigned)]
```

When trying to set up a new route, it is possible to search for station IDs (which apparently have *not* changed). However, saving a route always returns the error message `Unknown Start-Station (From) ... in Route 0`.

Probably related  to #289 and #288.

Maybe related to https://github.com/public-transport/hafas-client/issues/286 (i.e. HAFAS API no longer accepts certain user agents)

**Comment by mswiege** [comment]
The last successful query for me was on "31.03.2023 23:40", since then I always get the mentioned "Unknown Station" errors. Re-query of the stations in the admin interface still returns my station IDs unchanged, so they seem to be valid, but even when I try to save the changes in admin, it won't allow saving because it claims the unknown stations need to be fixed first.

**Comment by gaudes** [comment]
Hello,

sorry, seems that the Deutsche Bahn has changed something, see here:

https://github.com/public-transport/hafas-client/issues/288

I've just released a new version, hope it will get in stable as soon as possible.

Thanks and regards,

Ralf

**Comment by mswiege** [comment]
Can confirm that it is working again with this fix. Thank you @gaudes !
